server:
  port: 8094

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.30:3306/product_qiyue
    username: root
    password: 213316
  data:
    mongodb:
      uri: mongodb://192.168.1.4:27017/product_qiyue

  application:
    name: provider-yzh

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
